name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - ubuntu-22.04
        - ubuntu-latest
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v3
    - name: install packaged Rust compiler
      run: |
        rm -rf /usr/share/rust/.cargo/bin/
        sudo apt-get update
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get install rustc
      if: ${{matrix.os != 'ubuntu-latest'}}
    - name: check Rust compiler version
      run: |
        type rustc
        rustc --version
    - name: build
      run:
        make
    - name: run tests
      run:
        make test
    - name: instal
      run:
        make install PREFIX=~/.local
    - name: clean up
      run:
        make clean
    - name: run post-install tests
      run:
        make test-installed
    - name: check README syntax
      run: |
        pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et

